theme: jekyll-theme-leap-day
title: Restaurant Review App
description: Code Notes by James Priest

exclude: [
  Gemfile,
  Gemfile.lock,
  node_modules/,
  Gruntfile.js,
  package-lock.json,
  package.json,
  src/
]